# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907b19587f12e0a626ede201417c47049f2ee2278b273981536f3f99d937f110c5bf1b7a044cb17c858c523a60392e925ee926957ba5a5f1c53536ea29403019

test:
  secret_key_base: a65e2261b4346cd0c880a455495a64c4c07cc64e6db34b759e8babcbd27f2535e450eadbfea1b228cda20cd58764b538f80fd4f8bdf81de5e3f06f0a790710ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
